<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <RootNamespace>AdvancedTopics.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Polly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../DomainDrivenDesign/DomainDrivenDesign.csproj" />
    <ProjectReference Include="../../EventSourcing/EventSourcing.csproj" />
    <ProjectReference Include="../../Resilience/Resilience.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="FluentAssertions" />
  </ItemGroup>

</Project>
