using Microsoft.EntityFrameworkCore;

namespace EfCoreMigrations.Data;

/// <summary>
/// Contrasts with the <c>HasData</c> seed in <c>GenreConfiguration</c>.
///
/// Genres are a small, fixed lookup table -- perfect for <c>HasData</c>,
/// which is declarative, versioned, and diffed automatically by every future
/// migration. This demo catalog is different: it's the kind of sample data
/// you want present in every environment (including a freshly-provisioned
/// one) but that isn't part of the schema's permanent, version-controlled
/// shape, and that you might want to update independently of a migration
/// (no ID renumbering, no migration to write just to tweak a title).
///
/// The upsert is written as raw SQL via ExecuteSqlInterpolatedAsync rather
/// than "check with LINQ, then Add" -- INSERT ... ON CONFLICT is atomic and
/// safe under concurrent startups (two instances booting at once won't race
/// each other into a duplicate-key exception), where a
/// "does it exist? then insert" round trip is not.
/// </summary>
public static class SeedData
{
    public static async Task EnsureDemoDataAsync(AppDbContext context, CancellationToken cancellationToken = default)
    {
        // Explicit IDs make the upsert idempotent: running this on every
        // startup updates the same two rows instead of accumulating
        // duplicates. OVERRIDING SYSTEM VALUE is not needed here because
        // Npgsql maps int identity columns as GENERATED BY DEFAULT AS
        // IDENTITY, which accepts explicit values.
        await context.Database.ExecuteSqlInterpolatedAsync($"""
            INSERT INTO authors (id, name)
            VALUES (1000, 'Demo Author')
            ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name
            """, cancellationToken);

        await context.Database.ExecuteSqlInterpolatedAsync($"""
            INSERT INTO books (id, title, author_id, pages, rating, genre_id)
            VALUES (1000, 'Demo Book', 1000, 250, 4, 1)
            ON CONFLICT (id) DO UPDATE SET
                title = EXCLUDED.title,
                pages = EXCLUDED.pages,
                rating = EXCLUDED.rating,
                genre_id = EXCLUDED.genre_id
            """, cancellationToken);
    }
}
