<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <RootNamespace>CleanArchitecture.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/CleanArchitecture.Domain/CleanArchitecture.Domain.csproj" />
    <ProjectReference Include="../../src/CleanArchitecture.Application/CleanArchitecture.Application.csproj" />
    <ProjectReference Include="../../src/CleanArchitecture.Infrastructure/CleanArchitecture.Infrastructure.csproj" />
    <ProjectReference Include="../../src/CleanArchitecture.WebApi/CleanArchitecture.WebApi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="FluentAssertions" />
  </ItemGroup>

</Project>
